package risk.game.main;

import javax.swing.*;
import java.awt.*;
import java.util.Observable;
import java.util.Observer;

/**
 * Displays the UI of the main game play
 * @author shareenali
 * @version 0.1
 */

@SuppressWarnings("deprecation")
public class MainView implements Observer {
    private JPanel mainPanel;
    private JPanel leftPanel;
    private JPanel rightPanel;

    /**
     * Updates the view the observable notifies
     * @param o the model
     * @param arg identification string
     */
    @Override
    public void update(Observable o, Object arg) {

    }

    /**
     * Prepares the view w.r.t. children
     * @param panelPhase phase view
     * @param panelLogs logs view
     * @param panelWorld world view
     */
    void prepareView(JPanel panelPhase, JPanel panelLogs, JPanel panelWorld) {
        this.addPhaseView(panelPhase);
        this.addLogsView(panelLogs);
        this.addWorldView(panelWorld);
    }

    /**
     * Adds phase view into the UI
     * @param panel panel that contains phase view
     */
    private void addPhaseView(JPanel panel) {
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.NORTH;

        leftPanel.add(panel, gbc);
    }

    /**
     * Adds logs view into the UI
     * @param panel panel that contains the logs view
     */
    private void addLogsView(JPanel panel) {
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.CENTER;

        leftPanel.add(panel, gbc);
    }

    /**
     * Adds world view into the UI
     * @param panel panel that contains the world view
     */
    private void addWorldView(JPanel panel) {
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;

        rightPanel.add(panel, gbc);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(0, 0));
        leftPanel = new JPanel();
        leftPanel.setLayout(new GridBagLayout());
        mainPanel.add(leftPanel, BorderLayout.WEST);
        rightPanel = new JPanel();
        rightPanel.setLayout(new GridBagLayout());
        mainPanel.add(rightPanel, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
