package game.main;

import javax.swing.*;
import java.awt.*;
import java.util.Observable;
import java.util.Observer;

@SuppressWarnings("deprecation")
public class MainView implements Observer {
    private JPanel mainPanel;
    private JPanel leftPanel;
    private JPanel rightPanel;

    @Override
    public void update(Observable o, Object arg) {

    }

    void prepareView(JPanel panelPhase, JPanel panelLogs, JPanel panelWorld) {
        this.addPhaseView(panelPhase);
        this.addLogsView(panelLogs);
        this.addWorldView(panelWorld);
    }

    private void addPhaseView(JPanel panel) {
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.NORTH;

        leftPanel.add(panel, gbc);
    }

    private void addLogsView(JPanel panel) {
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.CENTER;

        leftPanel.add(panel, gbc);
    }

    private void addWorldView(JPanel panel) {
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;

        rightPanel.add(panel, gbc);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(0, 0));
        leftPanel = new JPanel();
        leftPanel.setLayout(new GridBagLayout());
        mainPanel.add(leftPanel, BorderLayout.WEST);
        rightPanel = new JPanel();
        rightPanel.setLayout(new GridBagLayout());
        mainPanel.add(rightPanel, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
