package risk.game.main.dialog;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;

public class CardDialog {
    private JPanel panelContent;
    private JScrollPane scrollContent;
    private JList listContent;

    private DefaultListModel<String> modelCards = new DefaultListModel<>();

    @SuppressWarnings("unchecked")
    public void setupCards(ArrayList<String> cards) {
        this.modelCards.removeAllElements();

        for (String card : cards) {
            this.modelCards.addElement(card);
        }

        this.listContent.setModel(this.modelCards);
    }

    public ArrayList<String> getSelectedCards() {
        ArrayList<String> cards = new ArrayList<>();
        int indices[] = this.listContent.getSelectedIndices();

        for (int i : indices) {
            cards.add(this.modelCards.get(i));
        }

        return cards;
    }

    public int showUi() {
        return JOptionPane.showOptionDialog(null, this.$$$getRootComponent$$$(), "Exchange cards",
            JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, null, null);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelContent = new JPanel();
        panelContent.setLayout(new BorderLayout(0, 0));
        scrollContent = new JScrollPane();
        scrollContent.setPreferredSize(new Dimension(50, 200));
        panelContent.add(scrollContent, BorderLayout.CENTER);
        listContent = new JList();
        scrollContent.setViewportView(listContent);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelContent;
    }
}
