package game.settings;

import javax.swing.*;
import java.awt.*;

public class SettingsView {
    private JPanel panel_settings;
    private JLabel label_title;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel_settings = new JPanel();
        panel_settings.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        label_title = new JLabel();
        label_title.setText("Game Settings");
        panel_settings.add(label_title);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel_settings;
    }
}
