package game.settings;

import javax.swing.*;
import java.awt.*;

/**
 * It initializes the view for Game Settings
 *
 * @author shareenali
 * @version 0.1
 */

public class SettingsView {
    private JPanel panelSettings;
    private JPanel panelTitle;
    private JLabel labelTitle;
    private JPanel panelContent;
    private JPanel panelNoPlayers;
    private JLabel labelNoPlayers;
    private JComboBox comboNoPlayers;
    private JPanel panelPlayers;
    private JPanel panelPlayer;
    private JLabel labelName;
    private JTextField textName;
    private JComboBox comboType;

    private DefaultComboBoxModel<Integer> modelNoPlayers = new DefaultComboBoxModel<>();

    /**
     * Initializes the default values in UI.
     */
    @SuppressWarnings("unchecked")
    void initializeValues() {
        this.modelNoPlayers.removeAllElements();

        for (int i = 2; i < 7; i++) {
            this.modelNoPlayers.addElement(i);
        }

        this.comboNoPlayers.setModel(this.modelNoPlayers);
    }

    void createPlayerInfoPanels() {
        int noOfPlayers = this.modelNoPlayers.getElementAt(this.comboNoPlayers.getSelectedIndex());


    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelSettings = new JPanel();
        panelSettings.setLayout(new BorderLayout(0, 0));
        panelTitle = new JPanel();
        panelTitle.setLayout(new GridBagLayout());
        panelSettings.add(panelTitle, BorderLayout.NORTH);
        labelTitle = new JLabel();
        Font labelTitleFont = this.$$$getFont$$$(null, -1, 16, labelTitle.getFont());
        if (labelTitleFont != null) labelTitle.setFont(labelTitleFont);
        labelTitle.setText("Game Settings");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.ipadx = 16;
        gbc.ipady = 16;
        panelTitle.add(labelTitle, gbc);
        panelContent = new JPanel();
        panelContent.setLayout(new BorderLayout(0, 0));
        panelSettings.add(panelContent, BorderLayout.CENTER);
        panelNoPlayers = new JPanel();
        panelNoPlayers.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panelContent.add(panelNoPlayers, BorderLayout.NORTH);
        labelNoPlayers = new JLabel();
        labelNoPlayers.setText("Number of Players:");
        panelNoPlayers.add(labelNoPlayers);
        comboNoPlayers = new JComboBox();
        panelNoPlayers.add(comboNoPlayers);
        panelPlayers = new JPanel();
        panelPlayers.setLayout(new BorderLayout(0, 0));
        panelContent.add(panelPlayers, BorderLayout.CENTER);
        panelPlayer = new JPanel();
        panelPlayer.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panelPlayers.add(panelPlayer, BorderLayout.CENTER);
        labelName = new JLabel();
        labelName.setText("Name:");
        panelPlayer.add(labelName);
        textName = new JTextField();
        textName.setPreferredSize(new Dimension(164, 27));
        panelPlayer.add(textName);
        comboType = new JComboBox();
        panelPlayer.add(comboType);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelSettings;
    }
}
