package risk;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;

/**
 * The view component for the entry point in game.
 *
 * @author shareenali
 * @version 0.1
 */

public class RiskView {
    private JPanel panel_risk;
    private JPanel panel_title;
    private JLabel label_title;
    private JPanel panel_content;
    private JButton button_new_game;
    private JButton button_edit_map;
    private JButton button_new_map;

    RiskView() { }

    /**
     * Binds the useful listeners to newGameButton
     *
     * @param listener onClick listener
     */
    void bindNewGameListener(ActionListener listener) {
        this.button_new_game.addActionListener(listener);
    }

    /**
     * Binds the useful listeners to new map button
     * @param listener onClick listener
     */
    void bindNewMapListener(ActionListener listener) {
        this.button_new_map.addActionListener(listener);
    }

    /**
     * Binds the useful listeners to edit map button
     * @param listener onClick listener
     */
    void bindEditMapListener(ActionListener listener) {
        this.button_edit_map.addActionListener(listener);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel_risk = new JPanel();
        panel_risk.setLayout(new BorderLayout(0, 0));
        panel_title = new JPanel();
        panel_title.setLayout(new GridBagLayout());
        panel_risk.add(panel_title, BorderLayout.NORTH);
        label_title = new JLabel();
        Font label_titleFont = this.$$$getFont$$$("Ayuthaya", -1, 24, label_title.getFont());
        if (label_titleFont != null) label_title.setFont(label_titleFont);
        label_title.setText("Risk");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.ipadx = 10;
        gbc.ipady = 10;
        panel_title.add(label_title, gbc);
        panel_content = new JPanel();
        panel_content.setLayout(new GridBagLayout());
        panel_risk.add(panel_content, BorderLayout.CENTER);
        button_new_game = new JButton();
        button_new_game.setText("New Game");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        panel_content.add(button_new_game, gbc);
        button_edit_map = new JButton();
        button_edit_map.setText("Edit Map");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel_content.add(button_edit_map, gbc);
        button_new_map = new JButton();
        button_new_map.setText("New Map");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel_content.add(button_new_map, gbc);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel_risk;
    }
}
