package risk;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;

/**
 * The view component for the entry point in game.
 *
 * @author shareenali
 * @version 0.2
 */

public class RiskView {
    private JPanel panelRisk;
    private JPanel panelTitle;
    private JLabel labelTitle;
    private JPanel panelContent;
    private JButton buttonNewGame;
    private JButton buttonEditMap;
    private JButton buttonNewMap;
    private JButton buttonLoadGame;

    RiskView() {
    }

    /**
     * Binds the useful listeners to newGameButton
     *
     * @param listener onClick listener
     */
    void bindNewGameListener(ActionListener listener) {
        this.buttonNewGame.addActionListener(listener);
    }

    /**
     * Binds the useful listeners to new map button
     *
     * @param listener onClick listener
     */
    void bindNewMapListener(ActionListener listener) {
        this.buttonNewMap.addActionListener(listener);
    }

    /**
     * Binds the useful listeners to edit map button
     *
     * @param listener onClick listener
     */
    void bindEditMapListener(ActionListener listener) {
        this.buttonEditMap.addActionListener(listener);
    }

    void bindLoadGameListener(ActionListener listener) {
        this.buttonLoadGame.addActionListener(listener);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelRisk = new JPanel();
        panelRisk.setLayout(new BorderLayout(0, 0));
        panelTitle = new JPanel();
        panelTitle.setLayout(new GridBagLayout());
        panelRisk.add(panelTitle, BorderLayout.NORTH);
        labelTitle = new JLabel();
        Font labelTitleFont = this.$$$getFont$$$(null, -1, 18, labelTitle.getFont());
        if (labelTitleFont != null) labelTitle.setFont(labelTitleFont);
        labelTitle.setText("Main Menu");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.ipadx = 10;
        gbc.ipady = 10;
        panelTitle.add(labelTitle, gbc);
        panelContent = new JPanel();
        panelContent.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panelRisk.add(panelContent, BorderLayout.CENTER);
        buttonNewGame = new JButton();
        buttonNewGame.setText("New Game");
        panelContent.add(buttonNewGame);
        buttonEditMap = new JButton();
        buttonEditMap.setText("Edit Map");
        panelContent.add(buttonEditMap);
        buttonNewMap = new JButton();
        buttonNewMap.setText("New Map");
        panelContent.add(buttonNewMap);
        buttonLoadGame = new JButton();
        buttonLoadGame.setText("Load Game");
        panelContent.add(buttonLoadGame);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelRisk;
    }
}
